#!/bin/bash
# 让 notify-send 提示 todo list 并播放声音提示；建议搭配 cron 使用；只能在家目录中运行；条目较多时只能显示最近的几项
# -*- encoding: utf-8; -*-
# (c) free software, GPLv3
# (c) pityonline E-mail: pityonline@gmail.com

todo="`todo`"
# notify-send -t 10000 "Check todo list!" && aplay /home/pity/message.wav 2>/dev/null
notify-send -t 10000 "Check TODO List!" "$todo" && aplay /home/pity/snd/check.wav 2>/dev/null
